return {
	{
		mode = { "n", "v" },
		{ "<leader>f", group = "Find" },
		{ "<leader>g", group = "Git" },
		{ "<leader>l", group = "LSP" },
		{ "<leader>c", group = "Code Manipulation" },
		{ "<leader>t", group = "Telescope" },
		{ "<leader>m", group = "Misc" },
		{ "<leader>n", group = "Snacks" },
		{ "<leader>x", group = "Trouble" },
		{ "<leader>u", group = "Toggle Stuff" },
		{ "<leader>W", group = "Workspace" },
		{ "<leader>r", group = "Replace & Rename" },
		{ "[", group = "Prevous" },
		{ "]", group = "Next" },
		{ "g", group = "Go to" },
    { "<leader><tab>", group = "Tabs" },

		-- Next ( ] )
		{ "]a", desc = "Next argument" },
		{ "]A", desc = "Last argument" },
		{ "]b", desc = "Next buffer" },
		{ "]B", desc = "Last buffer" },
		{ "]d", desc = "Next diagnostic" },
		{ "]D", desc = "Last diagnostic in buffer" },
		{ "]l", desc = "Next location list entry" },
		{ "]L", desc = "Last location list entry" },
		{ "]m", desc = "Next method start" },
		{ "]M", desc = "Next method end" },
		{ "]q", desc = "Next quickfix entry" },
		{ "]Q", desc = "Last quickfix entry" },
		{ "]s", desc = "Next misspelled word" },
		{ "]t", desc = "Next tag" },
		{ "]T", desc = "Last tag" },
		{ "]%", desc = "Next unmatched group" },
		{ "](", desc = "Next unmatched (" },
		{ "]<", desc = "Next unmatched <" },
		{ "]{", desc = "Next unmatched {" },
		{ "]<C-l>", desc = "Next file in location list" },
		{ "]<C-q>", desc = "Next file in quickfix list" },
		{ "]<C-t>", desc = "Next tag in tag stack" },
		{ "]<Space>", desc = "Add empty line below cursor" },

		-- Prev ( [ )
		{ "[a", desc = "Previous argument" },
		{ "[A", desc = "First argument" },
		{ "[b", desc = "Previous buffer" },
		{ "[B", desc = "First buffer" },
		{ "[d", desc = "Previous diagnostic" },
		{ "[D", desc = "First diagnostic in buffer" },
		{ "[l", desc = "Previous location list entry" },
		{ "[L", desc = "First location list entry" },
		{ "[m", desc = "Previous method start" },
		{ "[M", desc = "Previous method end" },
		{ "[q", desc = "Previous quickfix entry" },
		{ "[Q", desc = "First quickfix entry" },
		{ "[s", desc = "Previous misspelled word" },
		{ "[t", desc = "Previous tag" },
		{ "[T", desc = "First tag" },
		{ "[%", desc = "Previous unmatched group" },
		{ "[)", desc = "Previous unmatched )" },
		{ "[>", desc = "Previous unmatched >" },
		{ "[}", desc = "Previous unmatched }" },
		{ "[<C-l>", desc = "Previous file in location list" },
		{ "[<C-q>", desc = "Previous file in quickfix list" },
		{ "[<C-t>", desc = "Previous tag in tag stack" },
		{ "[<Space>", desc = "Add empty line above cursor" },

    -- Go to
    { "gO", desc = "Document symbols" },
    { "gra", desc = "Code action" },
    { "gri", desc = "Goto implementation" },
    { "grn", desc = "Rename symbol" },
    { "grr", desc = "References" },
    { "grt", desc = "Type definition" },
    { "grx", desc = "Run codelens" },
	},
}
