#   ▄▄▄· ▄▄▌   ▄▄▄·  ▄▄· ▄▄▄  ▪  ▄▄▄▄▄▄▄▄▄▄ ▄· ▄▌
#  ▐█ ▀█ ██•  ▐█ ▀█ ▐█ ▌▪▀▄ █·██ •██  •██  ▐█▪██▌
#  ▄█▀▀█ ██▪  ▄█▀▀█ ██ ▄▄▐▀▀▄ ▐█· ▐█.▪ ▐█.▪▐█▌▐█▪
#  ▐█ ▪▐▌▐█▌▐▌▐█ ▪▐▌▐███▌▐█•█▌▐█▌ ▐█▌· ▐█▌· ▐█▀·.
#   ▀  ▀ .▀▀▀  ▀  ▀ ·▀▀▀ .▀  ▀▀▀▀ ▀▀▀  ▀▀▀   ▀ •
#   ▄▄·        ▐ ▄ ·▄▄▄   ▄▄▄▄▄      • ▌ ▄ ·. ▄▄▌
#  ▐█ ▌▪▪     •█▌▐█▐▄▄·   •██  ▪     ·██ ▐███▪██•
#  ██ ▄▄ ▄█▀▄ ▐█▐▐▌██▪     ▐█.▪ ▄█▀▄ ▐█ ▌▐▌▐█·██▪
#  ▐███▌▐█▌.▐▌██▐█▌██▌.    ▐█▌·▐█▌.▐▌██ ██▌▐█▌▐█▌▐▌
#  ·▀▀▀  ▀█▄▀▪▀▀ █▪▀▀▀  ▀  ▀▀▀  ▀█▄▀▪▀▀  █▪▀▀▀.▀▀▀

# imports and sets up the colorscheme
import = [
	# "~/.config/alacritty/themes/themes/aura.toml" # aura theme (custom)
	"~/.config/alacritty/themes/themes/frozenembers.toml" # frozen embers theme
]

# changes the home directory the console opens in
working_directory = "c:/Users/Amal Lalgi"

# the cursor style
[cursor.style]
blinking = "On"
shape = "Block"

# font setup
[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Bold"

# scrolling history
[scrolling]
history = 10000

# sets the default shell
[shell]
args = ["--login"]
program = "C:/Program Files/Git/bin/bash"

# window setup
[window]
decorations = "full" # configs the title bar and the buttons
title = "Terminal" # the window name
dimensions = { columns = 110, lines = 30 } # size of the window
padding = { x = 8, y = 2 } # padding of the window
position = {x = 452, y = 8 } # position of the window when starting up

# hotkey config
[keyboard]
bindings = [
	{ key = "Back", mods = "Control", chars = "\u0017" }, # ctrl+bckspce - delete word
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" }, # creates a new window
	{ key = "v", mods = "Control", action = "Paste" }, # pastes with ctrl+v
]
