# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# boilerplate aliases
mcd() { mkdir -p "$1" && cd "$1"; }       # mcd: makes new dir and jumps inside
alias cic='set completion-ignore-case On' # cic: make tab-completion case-insensitive
alias mkdir='mkdir -pv'                   # creates the directory and the parents if necessary
alias cp='cp -iv'                         # shows verbose, displays the files being moved or renamed
alias mv='mv -iv'                         # shows verbose, displays the files being moved or renamed
