# colors
background            #051177
foreground            #c0c9c3
selection_background  #556b8d
selection_foreground  #c0c9c3
cursor                #c0c9c3
cursor_text_color     #051177

# black
color0  #0a0f2e
color8  #2a3050

# red
color1  #ff0000
color9  #ff3333

# green
color2  #00ff00
color10 #33ff33

# yellow
color3  #c8d4d0
color11 #e0ecf0

# blue
color4  #a0b4c0
color12 #c0d4e0

# magenta
color5  #b0c4c8
color13 #d0e4e8

# cyan
color6  #b8ccd0
color14 #d8ecf0

# white
color7  #c0c9c3
color15 #ffffff

url_color             #a0c0c8
tab_bar_style separator
tab_separator ""
tab_activity_symbol !
tab_title_template " {index}:{title}{fmt.fg._e39069}{activity_symbol}{fmt.fg.tab} "
active_tab_title_template " * {title} "
tab_bar_edge bottom
tab_bar_align left
active_tab_foreground   #c0c9c3
active_tab_background   #051177
inactive_tab_foreground #a0b4c0
inactive_tab_background #0a0f2e
tab_bar_background      #0a0f2e
tab_bar_margin_color    #0a0f2e
tab_bar_margin_width 0
tab_bar_margin_height 0 0
active_border_color     #c0d4e0
inactive_border_color   #2a3050
italic_font auto
font_features none
