-- ~/.config/hypr/modules/workspaces.lua
-- ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- "smart gaps" / "no gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name        = "no-gaps-wtv1",
--     match       = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name        = "no-gaps-f1",
--     match       = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- make the workspaces persistent (exists even when empty)
-- hl.workspace_rule({ workspace = "1", persistent = true })
-- hl.workspace_rule({ workspace = "2", persistent = true })
-- hl.workspace_rule({ workspace = "3", persistent = true })
-- hl.workspace_rule({ workspace = "4", persistent = true })
