#  ▐ ▄ ▄▄▄ .       ▌ ▐·▪  ·▄▄▄▄  ▄▄▄ .
# •█▌▐█▀▄.▀·▪     ▪█·█▌██ ██▪ ██ ▀▄.▀·
# ▐█▐▐▌▐▀▀▪▄ ▄█▀▄ ▐█▐█•▐█·▐█· ▐█▌▐▀▀▪▄
# ██▐█▌▐█▄▄▌▐█▌.▐▌ ███ ▐█▌██. ██ ▐█▄▄▌
# ▀▀ █▪ ▀▀▀  ▀█▄▀▪. ▀  ▀▀▀▀▀▀▀▀•  ▀▀▀ 

tabs = true
theme = "auto"
title-hidden = true
frame = "full"
# fork = false
# idle = true
# maximized = false
# no-multigrid = false
# srgb = false
# vsync = true
# wsl = false

[font]
normal = ['JetbrainsMono Nerd Font'] # Will use the bundled Fira Code Nerd Font by default
size = 11
